### PR TITLE
(feat) consistent gradient bg and title as hero

### PR DESCRIPTION
**Pull request by Holybasil**
only add the gradient bg to **bridge page** and **rollupscan page** as I am uncertain if it is suitable to add that to [blog page](https://scroll.io/blog).
furthermore, it seems unnecessary to add it to other pages.
feel free to leave feedbacks

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204621621249876

### CODE REVIEW

**Review by OrestTa — COMMENTED** [review]
Looking nice already! Still open, as discussed today:

1. Standardise header text + wallet button + put wallet button on same line
2. Add standardised header component to devportal-root page too

**Comment by Holybasil** [comment]
> Looking nice already! Still open, as discussed today:
> 
> 1. Standardise header text styling + wallet button + put wallet button on same line
> 2. Add standardised header component to devportal-root page too; copy for header title "Scroll Alpha Testnet", copy for header subtitle "Get started with our testnet now"

could you please help unify page headers on Figma according to descriptions above?  specially, portal page, bridge page and ecosystem page @yttriumli

**Comment by Holybasil** [comment]
after talking with @yttriumli , we would like to know the priority of this task in comparison to the footer redesign and other tasks that YTT currently has on hand. Additionally, we need to consider whether it is necessary to do this now in light of future rebranding efforts. Given the current scarcity of design resources, I can also unify them based on my own aesthetic judgement. @OrestTa

**Comment by OrestTa** [comment]
> after talking with @yttriumli , we would like to know the priority of this task in comparison to the footer redesign and other tasks that YTT currently has on hand. Additionally, we need to consider whether it is necessary to do this now in light of future rebranding efforts. Given the current scarcity of design resources, I can also unify them based on my own aesthetic judgement. @OrestTa

Thanks; if you could make a suggestion yourself, @Holybasil , I'd appreciate that a lot! (Either in Figma or, if you feel confident, here straight away).

**Comment by Holybasil** [comment]
taken all into consideration, I will unify the page header based on my aesthetic judgement. @OrestTa

**Review by OrestTa — APPROVED** [review]
Very neat, thank you! :)

**Pull request merged**
