### PR TITLE
fix: clearly distinguish between title and link

### PR DESCRIPTION
**Pull request by Holybasil**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204578436155149

### CODE REVIEW

**Comment by Holybasil** [comment]
> Regarding the footer, if we do not plan to make significant changes and want to follow the current scrolling website rule, we need to focus on making a clear distinction between the title and link, providing a better introduction to users to take action.
> 
> Here are some suggestions:
> 
> 1. Add hover and click interaction: The text of the link turns orange (#F18740).
> 2. If the group title has a higher information hierarchy than the link, it can be made larger to distinguish it from the link.
> 3. Adjust the font details, such as font weight \ size \ color.

pretty good~
could you please help update the footer in Figma design?

**Comment by yttriumli** [comment]
Sure, I will add this requirement in my work plan.🙌

**Comment by yttriumli** [comment]
Hey, there  @OrestTa @Holybasil @stateofkate I updated the footer according to the current specifications of the scroll official website, mainly dealing with the information hierarchy. Please have check thanks. Here is the Figma link:https://www.figma.com/file/kpMcaCEwT1eaW5gKo37heB/All-Scroll-Frontends?type=design&node-id=0%3A1&t=nNROPkwNBV730RXs-1

**Comment by OrestTa** [comment]
> Hey, there @OrestTa @Holybasil @stateofkate I updated the footer according to the current specifications of the scroll official website, mainly dealing with the information hierarchy. Please have check thanks. Here is the Figma link:https://www.figma.com/file/kpMcaCEwT1eaW5gKo37heB/All-Scroll-Frontends?type=design&node-id=0%3A1&t=nNROPkwNBV730RXs-1

Thanks so much. @stateofkate this is still a WIP, correct?

**Review by OrestTa — APPROVED** [review]

**Pull request merged**
