### PR TITLE
feat(bridge): ens support in custom recipient input

### PR DESCRIPTION
**Pull request by yqrashawn**
-------

## PR Summary
resolve GEN-1323
[comment]: Summarise the problem and how the pull request solves it
user can now use ens name in custom recipient input

---

## Checklist

- [ ] There are breaking changes
- [x] I've added/changed/removed ENV variable(s)
- [x] I checked whether I should update the docs and did so by updating `/docs`

---

[comment]: # (Please provide a more detailed description of your pull request here, explaining the changes made and the reasoning behind them)

### CODE REVIEW

**Comment by Holybasil** [comment]
CleanShot 2024-11-01 at 09 23 13@2x
the Remove button doesn't work @yqrashawn

**Comment by yqrashawn** [comment]
> CleanShot 2024-11-01 at 09 23 13@2x the Remove button doesn't work @yqrashawn

thanks for the review, this is fixed now

**Comment by zzq0826** [comment]
image

When "Customise recipient" is turned off, the error message should be removed. @yqrashawn

**Comment by yqrashawn** [comment]
thanks for the review @zzq0826 
it's fixed

**Review by Holybasil — APPROVED** [review]

**Pull request merged**
