### PR TITLE
feat (bridge): failed && canceled tx

### PR DESCRIPTION
**Pull request by Holybasil**
1. canceled and failed transactions will be removed when request list again and the error detail will error details will be reported to sentry and tagged as debug level (we can filter these errors precisely and check them)
2. accelerated transactions will replace old ones.
3. timeout for transactions that are not on chain is one hour, then they will be marked failed.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204430995804454
  - https://app.asana.com/0/0/1204546038752829
  - https://app.asana.com/0/0/1204359404412671
  - https://app.asana.com/0/0/1204368887911972

### CODE REVIEW

**Comment by Holybasil** [comment]
those failed transactions refer to the data that was **not recorded on the blockchain** for some reason but only recorded on the frontend. It means that the backend can't find the corresponding data. If we don't remove them, they will always appear at the top of the list, which means that the successful transactions sent later will be displayed after them. I think this is not quite appropriate. 
meanwhile, it will be deleted after cleaning local storage, even though I don't remove it when people reopen the bridge history popover.
@OrestTa

**Comment by OrestTa** [comment]
> those failed transactions refer to the data that was **not recorded on the blockchain** for some reason but only recorded on the frontend. It means that the backend can't find the corresponding data. If we don't remove them, they will always appear at the top of the list, which means that the successful transactions sent later will be displayed after them. I think this is not quite appropriate. meanwhile, it will be deleted after cleaning local storage, even though I don't remove it when people reopen the bridge history popover. @OrestTa

Thanks, makes sense. Can a tx "fail" here for another reason than a timeout wrt backend?

**Comment by Holybasil** [comment]
such as insufficient gas or an invalid opcode, the problem that @ChuhanJin met is insufficient gas. @OrestTa

**Comment by OrestTa** [comment]
> 

OK. So in such a case, we DO want to continue displaying such a 'failed' transaction, so we need to adjust the logic for

> 1. canceled and failed transactions will be removed when request list again and the error detail will error details will be reported to sentry and tagged as debug level (we can filter these errors precisely and check them)

correct?

**Comment by Holybasil** [comment]
> > 
> 
> OK. So in such a case, we DO want to continue displaying such a 'failed' transaction, so we need to adjust the logic for
> 
> > 1. canceled and failed transactions will be removed when request list again and the error detail will error details will be reported to sentry and tagged as debug level (we can filter these errors precisely and check them)
> 
> correct?

However, the data is not in the backend and can't be well displayed with the backend data considering sorting and paging I suggest adding a new tab called "Exception" where failed/cancelled transactions can be viewed which means those transactions can be placed separately. It should be noted that the data **will be deleted after cleaning local storage**.

**Review by OrestTa — DISMISSED** [review]
Decided to block this PR for now, cf. https://scrollco.slack.com/archives/C02PKAQ2430/p1681730492634489 and https://app.asana.com/0/1202293017617135/1204415067415477/f .

**Comment by OrestTa** [comment]
Failed transactions (here probably because of changed contract addresses) disappear from the history popup for me once they are no longer 'pending' - instead of being shown as 'failed'; example:

image

**Comment by Holybasil** [comment]
we should click the button on the right side of the address button to view the history data.

**Comment by OrestTa** [comment]
Oh oops wrong popup open in the screenshot; the correct popup doesn't show failed txes (at least some of them), e.g. if you manually set the gas limit too low, this happens:

image

**Comment by Holybasil** [comment]
yup, the way of catching error in ethers.js v6 is also changed, my original code doesn't work well.
I have communicated with the maintainer and will update it after receiving a solution.

**Comment by OrestTa** [comment]
> yup, the way of catching error in ethers.js v6 is also changed, my original code doesn't work well. I have communicated with the maintainer and will update it after receiving a solution.

Gotcha. Does it mean we need to block this PR on that, or can we release (a part of) it earlier?

**Comment by Holybasil** [comment]
this PR is aimed at solving multiple problems, feel free to let me know if there is anything unexpected. @OrestTa

**Comment by OrestTa** [comment]
Thanks. Still a draft or can it be reviewed and merged already? @Holybasil

**Comment by Holybasil** [comment]
Based on my self-testing, it can be reviewed. 
I have marked it as ready for review.

**Comment by OrestTa** [comment]
@Holybasil I submitted one L1->L2 and one L2->L1 tx and both were showing with the 'waiting animation' in the history; i then tried opening the console then but the tab crashed. Now, upon navigating to the bridge again, the tx history is empty, but there seem to be the two txes in the console - I assume this is not correct?

image

**Comment by OrestTa** [comment]
txes: 
- https://staging-blockscout.scroll.io/tx/0xcb8ba5f8be080797245b7162cfedb30022236e34372ea2cb3e0ad3b905bed80b
- https://goerli.etherscan.io/tx/0x4db8811daf966db9713c6bb7df566cca3d392959599f2f1ca6850231c64e1926

**Comment by OrestTa** [comment]
Thanks. So you added 1) now? Shall we add 2) already too? Btw, I was using brave wallet for this test.

**Comment by Holybasil** [comment]
> Thanks. So you added 1) now? Shall we add 2) already too? Btw, I was using brave wallet for this test.

1 and 2 are both added now, and it is better to clear localStorage manually before testing again.

**Review by OrestTa — APPROVED** [review]
Works well, thanks :)

**Pull request merged**
