### PR TITLE
fix: better persist estimatedEndTime

### PR DESCRIPTION
**Pull request by Holybasil**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204296239427634
  - https://app.asana.com/0/0/1204296239427636

### CODE REVIEW

**Comment by OrestTa** [comment]
I couldn't reproduce it though, so maybe a race condition?

**Comment by Holybasil** [comment]
let me test it again

**Comment by Holybasil** [comment]
I've updated the filter to prevent duplicate transactions on **Move More Funds** page.

**Review by OrestTa — APPROVED** [review]
Well done!

**Pull request merged**
