### PR TITLE
ecosystem improvements

### PR DESCRIPTION
**Pull request by Holybasil**
1. add loading indicator
2. deepened contour
3. bigger and farther link icons

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204367605288412

### CODE REVIEW

**Comment by OrestTa** [comment]
thx @Holybasil ; is this rdy for review? if so, could you request a gh reviewer, probably @zzq0826 usually, or myself if needed? thanks :)

**Comment by OrestTa** [comment]
Is the box drop shadow standardised/reused across all frontends already? 
<details><summary>Browser metadata</summary>





```
Path:      /alpha/ecosystem
Browser:   Chrome 112.0.0.0 on Mac OS 10.15.7
Viewport:  1512 x 836 @2x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-313--scroll-io.netlify.app%2Falpha%2Fecosystem&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=112.0&resolution=1512x836&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-313--scroll-io.netlify.app/alpha/ecosystem) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=643ce149877a790008857ba2&commentID=644121104a3a2c198d987eb0&resolution=resolved)

**Comment by OrestTa** [comment]
is the loading indicator supposed to show on logo-loading too? (it doesn't for me, only the whole-page which then lazy-loads logos)

**Comment by Holybasil** [comment]
> 

just for the whole gallery rather than separate logos, for the latter, I think we should first look at the outcome of [this task](https://app.asana.com/0/0/1204373412783359/f) before making any decisions.

**Review by yqrashawn — APPROVED** [review]

**Pull request merged**
