### PR TITLE
Implement new topbar

### PR DESCRIPTION
**Pull request by zzq0826**

### CODE REVIEW

**Comment by OrestTa** [comment]
5. Move "Rollup Explorer" to first position

**Comment by Holybasil** [comment]
**Both**
1. can we increase the spacing between the links? and the spacing between the summary titles as well?
2. can we make the link text bolder?

**Desktop**
1. can we highlight the entire rectangle instead of underlining the text when hovering?
2. can we set the unfold icon to rotate 180 degrees compared with the fold icon, instead of moving it down a little?
3. can we align the divider aligned with link text?

**Mobile**
1. can we exchange the fold and unfold icon?

**Uncertain But Concerned**
1. can we remove the outer orange border and add box shadow and apply a lighter background color? [Desktop]
2. can we remove the outer gray border and make the divider between the summary title full screen?  [Mobile]

**Comment by Holybasil** [comment]
applied unified page header on blog/team page

**Review by OrestTa — CHANGES_REQUESTED** [review]
Some of Yulan's and my change requests from above are still open, right?

**Comment by stateofkate** [comment]
Suggestion:
Reverse the arrow when the drop down is expanded such that the arrow points up vs when the drop down is unexpanded the arrow points down

**Comment by OrestTa** [comment]
> * can we highlight the entire rectangle instead of underlining the text when hovering?

Thanks, looks even better now! :)

`can we highlight the entire rectangle instead of underlining the text when hovering?` -> this is still pending as far as I see, and in particular, at least on desktop, it's still possible to tap a row such that the menu will be dismissed - instead of navigating to the target; e.g.:

image

**Comment by stateofkate0** [comment]
I think this is ready to deploy as is. @OrestTa I see your point with regards to feedback, but let's go for the 80/20 to deploy here ASAP. https://zksync.io/ also changes the text color, and if folks find it confusing on desktop they can just hit return.

**Review by OrestTa — APPROVED** [review]
Amazing work, everyone! :)

**Pull request merged**
